# Generated by Django 3.1.4 on 2021-01-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210129_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=False, max_length=200, unique=True),
        ),
    ]
